### PR TITLE
chore: remove package.json when only need manifest

### PR DESCRIPTION
**Pull request by Hongbo-Miao**
https://github.com/OfficeDev/generator-office/issues/257

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
@nokafor How do we expect customers to use the manifest only option? What work flows will include a validation option?

**Comment by nokafor** [comment]
Hey @MIchaelMainer we talked a bit offline about this, but I'm going to go ahead and merge this. Can we publish a new beta version to unblock the integration of yo office into other tooling? That way we don't affect the experience of people currently using Yo Office until there is a new getting started story in place.

**Comment by MIchaelMainer** [comment]
@nokafor I'm going to stop by your office :)

**Comment by nokafor** [comment]
@Hongbo-Miao can you submit this PR to the beta branch?

**Comment by Hongbo-Miao** [comment]
Done

**Pull request merged**
