### PR TITLE
Simplifying macOS certificate registration steps

### PR DESCRIPTION
**Pull request by davidchesnut**
Thank you for your pull request. Please provide the following information.

---

1. **Do these changes impact *User Experience*?** (e.g., how the user interacts with Yo Office and/or the files and folders the user sees in the project that Yo Office creates)
    > 
    > * [ ]  Yes
    > * [X]  No

    If Yes, briefly describe what is impacted.

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    > 
    > * [X]  Yes
    > * [ ]  No

    If Yes, briefly describe what is impacted.
I believe this is a simpler way to register certs on a mac.

3. **Validation/testing performed**:

    Describe manual testing done. 
I tested on a mac, but would be good to have someone double-check these steps.

4. **Platforms tested**:

    > * [ ] Windows
    > * [X] Mac

### CODE REVIEW

**Comment by akrantz** [comment]
Simplified steps look good. However, this assumes that you already have the dev-server running and can browse to https://localhost:3000 in Chrome. It might help to provide context, or to provide instructions using the file in the project. On Windows, you can open the certificate file and install it. Is there a similar step to get the certificate in Keychain Access?

**Comment by akrantz** [comment]
Also, I can double-check the steps tomorrow.

**Comment by TCourtneyOwen** [comment]
I’ll take a closer look tomorrow but I’m general looks good

**Comment by akrantz** [comment]
I was able to do `open certs` to open the certs folder in Finder.
Next, I double-clicked the ca.crt file.
When prompted for Keychain Access, I entered the password.
I think launched Keychain Access, found the localhost-ca certificate, and changed it to be trusted.

**Comment by akrantz** [comment]
My point is basically that you can do it from the file without having to use Chrome.

**Comment by davidchesnut** [comment]
@akrantz and @TCourtneyOwen okay updated steps to just use Finder. Does this work?

**Pull request merged**
