### PR TITLE
Template Modernization

### LINKED ISSUE #219: Add .gitignore, .vsproj, .sln, .deployment, .travis.yml, .nvmrc and a README to the project
Add .gitignore (with a set of Node + VS defaults (node_modules, bit, obj))
.vsproj and .sln (for Visual Studio)
And .deployment (for azure deployment, to specify dist folder)
.travis.yml (Travis continuous-integration)
maybe .nvmrc (Node Version Manager)

And a README to describe what all these files are, and the scenarios for when you need them.

### LINKED ISSUE #241: Add `OfficeJsHelpers` by default (e.g., esp. for error notifications and logging)
See the default snippet from Script Lab, and its use of Office Helpers in the catch block.  Both the UI utility and the logging are very helpful, and should be include in Yeoman as well.

    $("#run").click(run);

    async function run() {
        try {
            await Excel.run(async (context) => {
                const range = context.workbook.getSelectedRange();
                range.format.fill.color = "yellow";
                range.load("address");

                await context.sync()

                console.log(`The range address was "${range.address}".`);
            });
        }
        catch (error) {
            OfficeHelpers.UI.notify(error);
            OfficeHelpers.Utilities.log(error);
        }
    }

### LINKED ISSUE #243: Issues with default "run code"
A couple low-hanging-fruit issues:

- Code should do something (even as simple as showing a notification via `OfficeHelpers.UI.notify("Your code goes here")`, or better yet something that does something with the OM (set selection to a color, whatever).  Without this, I thought the hookup was broken.

- Code should absolutely have a try/catch.  It's both a best-practice, and the only sane way to see why something failed.  See related https://github.com/OfficeDev/generator-office/issues/241

image

### LINKED ISSUE #266: Need addtional setting in bsconfig.json
When a dev runs `npm start `on a taskpane add-in project generated with yo office, the home page of the taskpane automatically opens in the default browser of the developer's computer. This is default browser-sync behavior. But this is confusing to Office add-in devs because the add-in does not run in a browser, it runs in a taskpane. To change the default behavior the bsconfig.json needs one more setting, just below the `"files: "*.*"` setting. The new setting is: 
`"open": false`

### LINKED ISSUE #270: Add instructions to readme about how to run yo office from repo version
Anyone that wants to contribute to this repo will need to run their dev version of yo office. We should provide those instruction to lower bar to contribution.

### LINKED ISSUE #288: Update templates to webpack v4
Now that [webpack 4 has been released](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4) we should update the templates using webpack to use v4 rather than v3.

The bulk of this work will likely be reconfiguration of the webpack conifgs due to breaking changes in webpack from v3 => v4.

### LINKED ISSUE #289: Add babel + webpack to js templates
When devs say they want a js project they usually don't mean a pure un-optimized, un-transformed, un-polyfilled javascript solution, which is what our js templates currently provide.

### PR DESCRIPTION
**Pull request by casieber**
- Added babel+webpack (v4) to JS templates. Fixes #289, Fixes #288.
- Upgraded angular versions in angular templates
- Added dev instructions to the README. Fixes #270.
- Factored out host-specific starter code to a common location
- Added some base starter code beyond an empty "context.sync()". Fixes #243.
- Added `office-js-helpers` to templates and added logging for caught errors in starter snippets. Fixes #241.
- Fixed .gitignore not being copied into output templates. Fixes #219.
- Removed old bsconfig since we are using webpack only. Closes #266.
- Updated tests to use some common filepath variables where applicable.
- Updated tests to match all the new output directory structures.
- Fixed function-file's being included with templates other than react+ts.

### CODE REVIEW

**Comment by akrantz** [comment]
Can you fix these warnings?   This is for jquery-js.
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
```

**Comment by akrantz** [comment]
Also, are you going to add a react-js project?

**Comment by casieber** [comment]
> Can you fix these warnings? This is for jquery-js.

These warnings come from packages that are not our direct dependencies. For instance, the babel warning comes from installing webpack, even though we are on the latest version. So no, I cannot fix those.

Hopefully they will be fixed and merged as minor version updates to the packages we directly depend on, meaning they will go away without any intervention from us.

> Also, are you going to add a react-js project?

Not as part of this PR. Issue #286 is open for addressing that.

**Comment by jayrathi** [comment]
I am not able to add my comments for the specific files since I am not added as a reviewer, so providing them here -
For the tests, can you-
1. Provide a better description for each test? They all have the same description right now.
2. Add a few more files, like index.html, resource.html and app.css to the commonExpectedFiles?

**Comment by casieber** [comment]
@jayrathi:

> I see that you have removed the async/await syntax in the typescript templates. Any particular reason for this?

Yes, the JS projects don't support usage of async / await, so in order for the code snippet logic to be shared right now I'm using standard `.then()` instead.

> Provide a better description for each test? They all have the same description right now.

So they did have slightly different descriptions that noted the differences, but I've gone ahead and updated them to be a little more descriptive.

> Add a few more files, like index.html, resource.html and app.css to the commonExpectedFiles?

resource.html is the only one of those 3 that is common, so I've gone ahead and moved it. For app.css and index.html, the React/TS project has them in different locations. That should be resolved once that template is also upgraded to latest webpack and can use the same webpack configs that the others now use, but that's outside the scope of this PR.

**Comment by casieber** [comment]
This also happens to fix the newly opened PPT bug.

Fixes #293

**Pull request merged**
