### PR TITLE
remove deletion of project folders in test to improve execution time

### PR DESCRIPTION
**Pull request by TCourtneyOwen**
Thank you for your pull request. Please provide the following information.

---

1. **Do these changes impact *User Experience*?** (e.g., how the user interacts with Yo Office and/or the files and folders the user sees in the project that Yo Office creates)
    > 
    > * [ ]  Yes
    > * [X ]  No

    If Yes, briefly describe what is impacted.

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    > 
    > * [ ]  Yes
    > * [ X]  No

    If Yes, briefly describe what is impacted.

3. **Validation/testing performed**:

    Locally tested changes but need to test in our CI Pipeline as well to see if this improves test execution    time

4. **Platforms tested**:

    > * [ X] Windows
    > * [ X] Mac

### CODE REVIEW

**Comment by akrantz** [comment]
Am I correct in my assumption that each test builds into a separate folder, and the agent gets cleaned up automatically? The only issue is that if this is run on a developer's own machine, there is no cleanup.

**Comment by TCourtneyOwen** [comment]
The projects get created under the built generators folder.  When you run "npm run build" all projects will be deleted along with everything else in the generators folder, so we get automatic clean-u.  But of course the build process will take longer since all these project folders will need to be deleted

**Comment by TCourtneyOwen** [comment]
I think all my machines in my office must be shut off or something. I see that all the agent machines, which are located in my office, show as offline in the agent pool.  Additionally, I am not even able to remote connect to the machines.  So, until I can get these machines online, I can't really confirm if this is a valid change

**Comment by TCourtneyOwen** [comment]
Closing this PR since we really don't need to make tests any faster once we remove host from the matrix. We now install/build far fewer projects

**Pull request closed without merging**
