### PR TITLE
Update Custom Functions template

### PR DESCRIPTION
**Pull request by Zlatkovsky**
Add JSON schema, updated script reference, and simpler registration call

### CODE REVIEW

**Comment by Zlatkovsky** [comment]
@TCourtneyOwen , @akrantz :  ping.

**Comment by Zlatkovsky** [comment]
@TCourtneyOwen , what's the next step with this, after you approved it?  Is it you or someone else who merges it?  And how does it make it into NPM (is it automatically published?...)

**Comment by Zlatkovsky** [comment]
Sounds good.  I had validated on my end that the new template generates the desired output -- including testing it with Excel Online and Desktop.  Feel free to do your own testing, but it's good on my end.

**Comment by TCourtneyOwen** [comment]
The new version has been published as 1.2.12

**Pull request merged**
