### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by millerds**
Thank you for your pull request. Please provide the following information.

---

1. **Do these changes impact *User Experience*?** (e.g., how the user interacts with Yo Office and/or the files and folders the user sees in the project that Yo Office creates)
    > 
    > * [ ]  Yes
    > * [x]  No

    If Yes, briefly describe what is impacted.

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    > 
    > * [ ]  Yes
    > * [x]  No

    If Yes, briefly describe what is impacted.

3. **Validation/testing performed**:

    Running unit tests after updating package dependencies

4. **Platforms tested**:

    > * [x] Windows
    > * [ ] Mac

### CODE REVIEW

**Comment by millerds** [comment]
Currently tests fail due to the zip file getting downloaded to the wrong place.  Need to fix this before merging.

**Comment by igor-ribeiiro** [comment]
> Currently tests fail due to the zip file getting downloaded to the wrong place. Need to fix this before merging.

What .zip files is this? Please ping me when this PR is ready to be reviewed (or make it draft for now).

**Comment by millerds** [comment]
> > Currently tests fail due to the zip file getting downloaded to the wrong place. Need to fix this before merging.
> 
> What .zip files is this? Please ping me when this PR is ready to be reviewed (or make it draft for now).

generator works by downloading a zip file of the template from one of our template repo and then updating according to the user's input.

**Comment by millerds** [comment]
Found the problem and corrected it.  Thing should be working now.

**Review by igor-ribeiiro — APPROVED** [review]

**Pull request merged**
