### PR TITLE
Removing SSO template

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
Removing SSO option as it has a security vulnerability.

---

1. **Do these changes impact *User Experience*?** (e.g., how the user interacts with Yo Office and/or the files and folders the user sees in the project that Yo Office creates)
    > 
    > * [X]  Yes
    > * [ ]  No

There is no more SSO template option in yo office.

2. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    > 
    > * [X]  Yes
    > * [ ]  No

SSO documentation would be outdated given the template will be pulled out.

3. **Validation/testing performed**:

`npm run test`.
Link yo office and test that SSO option is not there.

4. **Platforms tested**:

    > * [X] Windows
    > * [ ] Mac

### CODE REVIEW

**Review by Rick-Kirkham — APPROVED** [review]

**Comment by akrantz** [comment]
Aren't you going to add the SSO project back later? Rather than remove all the code and the test, just update the code so it excludes the project from being shown, and you can mark the test as "test.skip"

**Review by akrantz — CHANGES_REQUESTED** [review]
see comment

**Comment by akrantz** [comment]
Can't you just remove the SSO project from the list returned from the function that provides the project template names?

**Comment by igor-ribeiiro** [comment]
> Can't you just remove the SSO project from the list returned from the function that provides the project template names?

Sure, Louis made a commit to do that already. As it is already in master (the removal of SSO in the json file), I will be closing this PR

**Pull request closed without merging**
