### PR TITLE
Replaced gulp web server with browsersync.io and minor fixes

### PR DESCRIPTION
**Pull request by StfBauer**
Main part of this pull request is the replacement of gulp-webserver to [browsersync.io](http://www.browsersync.io). gulp-webserver was replaced in all project types.

gulp-webserver references in the documentation have been updated too. The procedure to add the self signed certificate hasn't changed.

In addition to this all generators have been separately tested and failing script and css links have been fixed.

### CODE REVIEW

**Comment by jthake** [comment]
I pulled this down to test. Apologies for the delay and got this error on testing the yeoman generator on Windows 10. The generator is working fine in master and dev branch when i checkout those. 

It appears that there are some dependencies that are required now that are different including having Python present. I'm not sure we want to add additional installs other than Node on here unless you have a hugely compelling reason for this?

````
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

> bufferutil@1.2.1 install C:\Users\jthake\git\generatorsamples\newaddin1\node_modules\bufferutil
> node-gyp rebuild


C:\Users\jthake\git\generatorsamples\newaddin1\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jthake\git\generatorsamples\newaddin1\node_modules\bufferutil
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\Users\jthake\git\generatorsamples\newaddin1\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\jthake\git\generatorsamples\newaddin1\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jthake\git\generatorsamples\newaddin1\node_modules\utf-8-validate
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

````

**Comment by StfBauer** [comment]
@jthake Thank you for testing and your feedback. Actually there is no dependency to have python installed first because node-gyp is a cross platform compiler bundled with nodejs and coming from the node js team. I will try to install it on a fresh new windows 10 VM because I saw similar issues with VSO Builds too. On my Windows 10 I have a full Version of the latest VS installed too but I'll try this without. I'll get back to you as soon as I found the issue on this.

**Comment by StfBauer** [comment]
@jthake Figured it out. Installed a new VM. Installed all the prerequisites and failed with the default web app generator of Yeoman as you did.
At this time I haven't had Visual Studio installed. After I installed the community edition node-gyp worked without any problem. I think its show stopper.
Actually even browser sync recommend to install Visual Studio on Windows to get around this. 

>Having trouble installing Browsersync on Windows? The most common reason for npm to throw errors when compiling Browsersync is that some of the dependencies (e.g. node-gyp need Visual C++ runtime libraries. [https://www.browsersync.io/docs/](https://www.browsersync.io/docs/)

What I installed on Window in addition to Visual Studio Community Edition was [Microsoft NodeJs Tools](https://github.com/Microsoft/nodejstools/)

Not sure what to do. It's up to you. Browser Sync Offer a lot of benefit especially when you develop in the Office Apps. It saves a lot time because of the automatically refreshes when you change the code. Plus the ability to sync different browsers and bandwidth.

I mean potentially you cannot use performance enhanced and natively compiled developer tools built for node because without VS you don't have much option. To be honest it would be interesting to see how this can be solved. (e.g. Install just this package from Microsoft and you are ready to go).
There are lot of speculations on this issue and many complain about.

**Comment by andrewconnell** [comment]
Feel free to dismiss this, but from my POV…

The value you get from doing web dev with browser sync is awesome and worth the cost to learn it. If you’re living in Visual Studio, you don’t need it because you have the linking tool they provide.

Today the generator is primarily for those buildings Office Add-ins not on Windows and instead on OS X/Linux. In this scenario, it’s not an issue from my POV because it’s only Windows that’s the issue.

Now with that being said, I know OfficeDev doesn’t like the statement I made above because they do see this as a faster way to get stuff out instead of waiting on Visual Studio proper. So in that case, having a “if you are on Windows, to do live development of this, you need a copy of Visual Studio per the browsersync docs, the free VS will do”. Point to the issue but also explain why browser sync is used.

**Comment by StfBauer** [comment]
Ok finished now my tests what is missing and why @jthake was asked for python. The minimum requirement for Windows User is to have [Visual C++ Redistribution](https://support.microsoft.com/en-us/kb/2977003) Runtime installed.

**Comment by jthake** [comment]
can you please pull down the last origin master and get this branch up to date?

**Comment by jthake** [comment]
also i stil get this after installing

$ yo office

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   Welcome to the Office  |
   `---------´   |   Project generator, by  |
    ( _´U`_ )    | @OfficeDev! Let's create |
    /___A___\    |    a project together!   |
     |  ~  |     '--------------------------'
   __'.___.'__
 ´   `  |° ´ Y `

? Project name (display name): (My Office Project) 005
? Project name (display name): 005
? Root folder of project? Default to current directory
? Root folder of project? Default to current directory
 (C:\Users\jthake\test\005), or specify relative path
 from current (src / public):
? Office project type: (Use arrow keys)
? Office project type: Mail Add-in (read & compose forms)
? Technology to use: (Use arrow keys)
? Technology to use: HTML, CSS & JavaScript
? Supported Outlook forms: (Press <space> to select)
? Supported Outlook forms: E-Mail message - read form, E-Mail message - compose
   create bower.json read form, Appointment - compose form
   create package.json
   create tsd.json
   create .bowerrc
   create gulpfile.js
   create content\Office.css
   create images\close.png
   create scripts\MicrosoftAjax.js
   create jsconfig.json
   create tsconfig.json
   create manifest-005.xml
   create manifest.xsd
   create appcompose\app.css
   create appcompose\app.js
   create appcompose\home\home.html
   create appcompose\home\home.css
   create appcompose\home\home.js
   create appread\app.css
   create appread\app.js
   create appread\home\home.html
   create appread\home\home.css
   create appread\home\home.js
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

> bufferutil@1.2.1 install C:\Users\jthake\test\005\node_modules\bufferutil
> node-gyp rebuild


C:\Users\jthake\test\005\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jthake\test\005\node_modules\bufferutil
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\Users\jthake\test\005\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\jthake\test\005\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jthake\test\005\node_modules\utf-8-validate
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

> 005@0.1.0 postinstall C:\Users\jthake\test\005
> bower install

bower microsoft.office.js#* not-cached git://github.com/andrewconnell/bower-MicrosoftOfficeJs.git#*
bower microsoft.office.js#*    resolve git://github.com/andrewconnell/bower-MicrosoftOfficeJs.git#*
bower jquery#~1.9.1             cached git://github.com/jquery/jquery-dist.git#1.9.1
bower jquery#~1.9.1           validate 1.9.1 against git://github.com/jquery/jquery-dist.git#~1.9.1
bower office-ui-fabric#*        cached git://github.com/OfficeDev/Office-UI-Fabric.git#1.2.1
bower office-ui-fabric#*      validate 1.2.1 against git://github.com/OfficeDev/Office-UI-Fabric.git#*
bower microsoft.office.js#*   checkout master
bower microsoft.office.js#*   resolved git://github.com/andrewconnell/bower-MicrosoftOfficeJs.git#1a54a322c7
bower jquery#~1.9.1            install jquery#1.9.1
bower office-ui-fabric#*       install office-ui-fabric#1.2.1
bower microsoft.office.js#*    install microsoft.office.js#1a54a322c7

jquery#1.9.1 bower_components\jquery

office-ui-fabric#1.2.1 bower_components\office-ui-fabric

microsoft.office.js#1a54a322c7 bower_components\microsoft.office.js
005@0.1.0 C:\Users\jthake\test\005
├─┬ browser-sync@2.11.1
│ ├── async-each-series@0.1.1
│ ├─┬ browser-sync-client@2.4.1
│ │ ├── etag@1.7.0
│ │ └── fresh@0.3.0
│ ├─┬ browser-sync-ui@0.5.17
│ │ ├── async-each-series@1.1.0
│ │ ├── connect-history-api-fallback@1.1.0
│ │ ├─┬ stream-throttle@0.1.3
│ │ │ ├── commander@2.9.0
│ │ │ └── limiter@1.1.0
│ │ └─┬ weinre@2.0.0-pre-I0Z7U9OV
│ │   ├─┬ express@2.5.11
│ │   │ ├─┬ connect@1.9.2
│ │   │ │ └── formidable@1.0.17
│ │   │ ├── mime@1.2.4
│ │   │ ├── mkdirp@0.3.0
│ │   │ └── qs@0.4.2
│ │   ├─┬ nopt@3.0.6
│ │   │ └── abbrev@1.0.7
│ │   └── underscore@1.7.0
│ ├── bs-recipes@1.0.5
│ ├─┬ chokidar@1.4.1
│ │ ├── anymatch@1.3.0
│ │ ├── async-each@0.1.6
│ │ ├── glob-parent@2.0.0
│ │ ├── inherits@2.0.1
│ │ ├─┬ is-binary-path@1.0.1
│ │ │ └── binary-extensions@1.4.0
│ │ ├── is-glob@2.0.1
│ │ ├── path-is-absolute@1.0.0
│ │ └── readdirp@2.0.0
│ ├─┬ connect@3.4.1
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├─┬ finalhandler@0.4.1
│ │ │ ├─┬ on-finished@2.3.0
│ │ │ │ └── ee-first@1.1.1
│ │ │ └── unpipe@1.0.0
│ │ ├── parseurl@1.3.1
│ │ └── utils-merge@1.0.0
│ ├── dev-ip@1.0.1
│ ├── easy-extender@2.3.2
│ ├─┬ eazy-logger@2.1.2
│ │ ├── opt-merger@1.1.1
│ │ └─┬ tfunk@3.0.1
│ │   ├─┬ chalk@0.5.1
│ │   │ ├── ansi-styles@1.1.0
│ │   │ ├─┬ has-ansi@0.1.0
│ │   │ │ └── ansi-regex@0.2.1
│ │   │ ├── strip-ansi@0.3.0
│ │   │ └── supports-color@0.2.0
│ │   └── object-path@0.9.2
│ ├── emitter-steward@1.0.0
│ ├─┬ foxy@11.1.4
│ │ ├─┬ http-proxy@1.13.0
│ │ │ ├── eventemitter3@1.1.1
│ │ │ └── requires-port@1.0.0
│ │ ├─┬ lodash.merge@3.3.2
│ │ │ ├── lodash._arraycopy@3.0.0
│ │ │ ├── lodash._arrayeach@3.0.0
│ │ │ ├─┬ lodash._createassigner@3.1.1
│ │ │ │ └── lodash._bindcallback@3.0.1
│ │ │ ├── lodash._getnative@3.9.1
│ │ │ ├── lodash.isarguments@3.0.5
│ │ │ ├── lodash.isarray@3.0.4
│ │ │ ├─┬ lodash.isplainobject@3.2.0
│ │ │ │ └── lodash._basefor@3.0.3
│ │ │ ├── lodash.istypedarray@3.0.3
│ │ │ ├── lodash.keys@3.1.2
│ │ │ ├── lodash.keysin@3.0.8
│ │ │ └── lodash.toplainobject@3.0.0
│ │ └── resp-modifier@4.0.4
│ ├─┬ fs-extra@0.26.5
│ │ ├── graceful-fs@4.1.2
│ │ ├── jsonfile@2.2.3
│ │ └── klaw@1.1.3
│ ├── immutable@3.7.6
│ ├─┬ localtunnel@1.8.1
│ │ ├── openurl@1.1.0
│ │ ├─┬ request@2.65.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── bl@1.0.1
│ │ │ ├── caseless@0.11.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.0
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@1.0.0-rc3
│ │ │ │ └── async@1.5.2
│ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ └─┬ is-my-json-valid@2.12.4
│ │ │ │   ├── generate-function@2.0.0
│ │ │ │   ├─┬ generate-object-property@1.2.0
│ │ │ │   │ └── is-property@1.0.2
│ │ │ │   └── jsonpointer@2.0.0
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├── boom@2.10.1
│ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └── sntp@1.0.9
│ │ │ ├─┬ http-signature@0.11.0
│ │ │ │ ├── asn1@0.1.11
│ │ │ │ ├── assert-plus@0.1.5
│ │ │ │ └── ctype@0.5.3
│ │ │ ├── isstream@0.1.2
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├── node-uuid@1.4.7
│ │ │ ├── oauth-sign@0.8.0
│ │ │ ├── qs@5.2.0

**Comment by StfBauer** [comment]
Thank you for the update. This can be resolved by:
```npm rebuild -g```

This force all C++ node.js modules to recompile. After that the message should be gone.

**Comment by StfBauer** [comment]
Dug a little bit deeper on your problem @jthake. While the default generators seem to install no optional components of browser-sync. Yo Office install those components. This has probably something to do how the generator install npm packages.
What I do now is to create my new test generator form scratch to evaluate how this problem can be avoided.
Head a great conversation on my blog today and this are the newest thing so far.

**Comment by andrewconnell** [comment]
The generator runs NPM INSTALL right after it scaffolds the project, but you can optionally skip that... YO OFFICE has a command line option flag you can specify: `--skip-install` It's one of the things I added in the first release: https://github.com/OfficeDev/generator-office#--skip-install

**Comment by StfBauer** [comment]
I know @andrewconnell . What I'm curious about is how the default generators (generator-webapp and generator-gulp-webapp) handle this situation because they have built in browser-sync support there too and don't have the same problem.
There must be somewhere a code inside that handle these optional components and avoid the installation.
You got the same information there:

```npm WARN install Couldn't install optional dependency: Unsupported```

Without installing the optional components.

**Comment by andrewconnell** [comment]
Hmmmm… that’s interesting. Warrants more investigation…

**Comment by StfBauer** [comment]
Ok. I figured it out now.

The origin of the problem is the npm package '[ws](https://www.npmjs.com/package/ws)' a web socket implementation, which is part of [socket.io](https://github.com/socketio), which is part of [browser-sync](https://www.npmjs.com/package/browser-sync).

The two dependencies that fail to compile are optional and performance optimized parts of 'ws' compiled in C++. To be more specific they are named 'bufferutil' and 'utf-8-validate'.

Node-gyp, which is a node core component, work only in any case when VC++ and Python is installed.
Alternative there is the option that the full version of Visual Studio is installed. (At least the community edition).

I rechecked the default generator-webapp and generator-gulp-webapp once again. Sadly those have the same problem and use the native implementation based on node.js instead of integrating the C++ compiled version.

My personal conclusion is that if you like to use the whole spectrum of Node.js developemnt you have to install Visual Studio or install Python 2.7. All because node-gyp, a core nodes module, doesn't work that well on Windows.

Anyway. It was a really awesome experience for me and I learned a lot. At least I got a really good technical insight on node.js and node.js on Windows ;)

I give up on this but will write a blog post on how to integrate browser-sync into generator-office. It is done just with a few steps.

```npm install browser-sync --no-optional``` doesn't throw an error because npm doesn't even try to install the optional components.

I already spent to much time on this issue. Will better focus on integrating wiredep and inject into this project.

I will close this PR tomorrow.

**Comment by jthake** [comment]
Thanks for investigating this @StfBauer . I appreciate your tenacity here! This is honestly out of my depth and can't add much more here so lets leave as is for now.

**Comment by StfBauer** [comment]
Thank you @jthake.

**Pull request closed without merging**
