### PR TITLE
Option to include Office UI Fabric for ng & ng-adal

### PR DESCRIPTION
**Pull request by rolandoldengarm**
Added a prompt and an option to include the ngOfficeUIFabric library.
Added test scripts to verify that it's added to bower.json

Solves https://github.com/OfficeDev/generator-office/issues/145

### CODE REVIEW

**Comment by rolandoldengarm** [comment]
I realize there is one thing to do: The module should be added as a dependency to the angular module definition when ngOfficeUIFabric is included.
Before I can test that, PR https://github.com/OfficeDev/generator-office/pull/149 has to be merged first.

**Comment by rolandoldengarm** [comment]
Done above. I've tested it by updating index.html manually.
PR is ready for review.

**Comment by jthake** [comment]
@andrewconnell as someone who has been a champion on this new angular bits...what are your thoughts on this?

**Comment by jthake** [comment]
@rolandoldengarm hey i just checked this, if you look at the diffs, this is a few commits behind the dev branch now. You can see its removing some of the other work (default . bits). Can you fix this branch and post here when done?

**Comment by andrewconnell** [comment]
I'll take a look tomorrow... Limited to iPad for reminder of the evening :)

**Comment by rolandoldengarm** [comment]
@jthake Rebased again, should be good now hopefully.

**Comment by jthake** [comment]
@rolandoldengarm  nope check out first file here https://github.com/OfficeDev/generator-office/pull/153/files

**Comment by rolandoldengarm** [comment]
Hmm yeah I see, no idea how that is possible. 
I've created a new branch of the issue-145 branch and submitted a new PR. That one is clean: https://github.com/OfficeDev/generator-office/pull/157

**Pull request closed without merging**
