### PR TITLE
Option to include Office UI Fabric for ng & ng-adal v2

### PR DESCRIPTION
**Pull request by rolandoldengarm**
Added a prompt and an option to include the ngOfficeUIFabric library.
Added test scripts to verify that it's added to bower.json

Solves #145

### CODE REVIEW

**Comment by rolandoldengarm** [comment]
@jthake Any ETA when this will be merged? I want to write a blog post about it...

**Comment by rolandoldengarm** [comment]
It's a bit of a shame that I spent quite some time to implement this, but that this is not being merged :( @jthake

**Comment by beth-panx** [comment]
Hey @rolandoldengarm I am merging your changes to the Dev branch today. I am still testing it myself. I will merge this into master once I am done. :)

**Comment by beth-panx** [comment]
Close and reopen to trigger checks..

**Comment by beth-panx** [comment]
@rolandoldengarm I also got couple errors running tests after merging your changes locally. Please see attached as an example. Same error is thrown for every file with ngofficeuifabric option implemented. 
screen shot 2016-10-11 at 9 52 35 am

**Comment by beth-panx** [comment]
In the new structure, we includes Office UI fabric in package.json which uses the new Fabric Core and Fabric JS. Close this PR.

**Pull request closed without merging**
